;Don't modify. If you want to change things, create a file named config.ini instead
[Global]

[database.out]
type = sqlite
uri = db/out.db
port =
options=
database =
username =
;Password should be in the env variable IN_PASSWORD
;For connecting to sqlserver use
;type = mssql+pyodbc
;uri = host
;port =
;options = driver=ODBC+Driver+17+for+SQL+Server
;database = database
;username = username

[server]
; time to wait for new data, in minutes
wait = 10
threads = 10

